language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
virtualenv:
  system_site_packages: true
install:
  - sudo apt-get install -y libblas-dev liblapack-dev libatlas-base-dev gfortran python-numpy python-scipy
  - pip install -r requirements.txt
script: pytest tests/test.py -v
