language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - sudo apt-get install libblas-dev liblapack-dev libatlas-base-dev gfortran
  - pip install -r requirements.txt
script: pytest tests/test.py -v
